environment:
  - "@air"
  - "@spawn"
  - "@cliff"
  - "@build1"
  - "@build2"
  - "@build3"
  - "@build4"
  - "@build5"
  - "@build6"
  - "@build7"
  - "@build8"
  - "@build9"
  - "@build10"
  - "@build11"
  - "@build12"
  - "@build13"
  - "@build14"
  - "@build15"
  - "@build16"
  - "@deep-water"
  - "@shallow-water"
  - "@tainted-water"
  - "@deep-tainted-water"
  - "@darksand-tainted-water"
  - "@sand-water"
  - "@darksand-water"
  - "@tar"
  - "@pooled-cryofluid"
  - "@molten-slag"
  - "@space"
  - "@empty"
  - "@stone"
  - "@crater-stone"
  - "@char"
  - "@basalt"
  - "@hotrock"
  - "@magmarock"
  - "@sand-floor"
  - "@darksand"
  - "@dirt"
  - "@mud"
  - "@dacite"
  - "@rhyolite"
  - "@rhyolite-crater"
  - "@rough-rhyolite"
  - "@regolith"
  - "@yellow-stone"
  - "@carbon-stone"
  - "@ferric-stone"
  - "@ferric-craters"
  - "@beryllic-stone"
  - "@crystalline-stone"
  - "@crystal-floor"
  - "@yellow-stone-plates"
  - "@red-stone"
  - "@dense-red-stone"
  - "@red-ice"
  - "@arkycite-floor"
  - "@arkyic-stone"
  - "@rhyolite-vent"
  - "@carbon-vent"
  - "@arkyic-vent"
  - "@yellow-stone-vent"
  - "@red-stone-vent"
  - "@crystalline-vent"
  - "@redmat"
  - "@bluemat"
  - "@grass"
  - "@salt"
  - "@snow"
  - "@ice"
  - "@ice-snow"
  - "@shale"
  - "@moss"
  - "@core-zone"
  - "@spore-moss"
  - "@stone-wall"
  - "@spore-wall"
  - "@dirt-wall"
  - "@dacite-wall"
  - "@ice-wall"
  - "@snow-wall"
  - "@dune-wall"
  - "@regolith-wall"
  - "@yellow-stone-wall"
  - "@rhyolite-wall"
  - "@carbon-wall"
  - "@ferric-stone-wall"
  - "@beryllic-stone-wall"
  - "@arkyic-wall"
  - "@crystalline-stone-wall"
  - "@red-ice-wall"
  - "@red-stone-wall"
  - "@red-diamond-wall"
  - "@sand-wall"
  - "@salt-wall"
  - "@shrubs"
  - "@shale-wall"
  - "@spore-pine"
  - "@snow-pine"
  - "@pine"
  - "@white-tree-dead"
  - "@white-tree"
  - "@spore-cluster"
  - "@redweed"
  - "@pur-bush"
  - "@yellowcoral"
  - "@boulder"
  - "@snow-boulder"
  - "@shale-boulder"
  - "@sand-boulder"
  - "@dacite-boulder"
  - "@basalt-boulder"
  - "@carbon-boulder"
  - "@ferric-boulder"
  - "@beryllic-boulder"
  - "@yellow-stone-boulder"
  - "@arkyic-boulder"
  - "@crystal-cluster"
  - "@vibrant-crystal-cluster"
  - "@crystal-blocks"
  - "@crystal-orbs"
  - "@crystalline-boulder"
  - "@red-ice-boulder"
  - "@rhyolite-boulder"
  - "@red-stone-boulder"
  - "@metal-floor"
  - "@metal-floor-damaged"
  - "@metal-floor-2"
  - "@metal-floor-3"
  - "@metal-floor-4"
  - "@metal-floor-5"
  - "@dark-panel-1"
  - "@dark-panel-2"
  - "@dark-panel-3"
  - "@dark-panel-4"
  - "@dark-panel-5"
  - "@dark-panel-6"
  - "@dark-metal"
  - "@pebbles"
  - "@tendrils"
  - "@ore-copper"
  - "@ore-lead"
  - "@ore-scrap"
  - "@ore-coal"
  - "@ore-titanium"
  - "@ore-thorium"
  - "@ore-beryllium"
  - "@ore-tungsten"
  - "@ore-crystal-thorium"
  - "@ore-wall-thorium"
  - "@ore-wall-beryllium"
  - "@graphitic-wall"
  - "@ore-wall-tungsten"

